### ISSUE TITLE
Transaction fetch should return bad request if given transaction number does not match transaction time hash

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-bitcoin#12]
Transaction fetch should return bad request instead of not-found if given transaction number does not match transasction time hash:

```javascript
      // return HTTP 404 if the requested transactionNumber does not match the transactionTimeHash
      if (verifyResponseBody['match'] === false) {
        return {
          status: ResponseStatus.NotFound,
          body: {}
        };
      }
```

**Comment by srinathsetty** [comment]
The spec says: “The transaction time hash helps the blockchain layer detect block reorganizations (temporary forks) and inform the requester using HTTP 404 on such events.“

Are we updating the spec?

**Comment by thehenrytsai** [comment]
You are right, I will update the spec immediately.

**Comment by srinathsetty** [comment]
Closing the issue given the PR was merged.
