### ISSUE TITLE
Fetch transaction does not return the transactions within the same block

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-bitcoin#13]
e.g.

http://127.0.0.1:3009/transactions?since=6212927891701761&transaction-time-hash=000000000000002deb21a9b78c381179bccf84aa7fc0db4e1a0cc37cf46ad199

should return transaction 6212927891701761 and 6212927891701762, but does not.

**Comment by srinathsetty** [comment]
Closing the issue since there is a different issue tracking one of the unaddressed comments, and code changes for this issue are merged with master.
