### ISSUE TITLE
Fetch API - Return based on transaction count rather than one block at a time

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-bitcoin#15]
Current implementation seems to be returning transactions in a block at a time, such batch size is really small and thus should be more efficient.

We should have a configurable transaction batch count e.g. (1000), and only return the batch when the batch size is met (or of course when there are no more transactions to be batched).

**Comment by srinathsetty** [comment]
Closing the issue since we merged the PR.
