### ISSUE TITLE
Investigate, upgrade, and document Node.js version support for bitcored dependency

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-bitcoin#29]
Currently Node.js v4 is documented supported version by bitcored, which is rather old. Ideally we would like to run bitcored on v10.

Investigate, upgrade, and document Node.js version support.

It appears that at least v8 is supported:

https://github.com/bitpay/bitcore/tree/v8.0.0

**Comment by srinathsetty** [comment]
Closing since the PR was merged.
