### ISSUE TITLE
Provide a Bitcoin transaction payment mechanism

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-bitcoin#30]
Design and implement how bitcoin wallet secret can be loaded and secured in a service environment.

**Comment by csuwildcat** [comment]
@srinathtv given we are approaching a public announcement to folks who will be attempting to run Write-enabled nodes, we need to settle on at least a first, basic mechanism/scheme for adding the required secret/wallet hooks to pay for Sidetree txns in Bitcoin.

**Comment by srinathsetty** [comment]
Closing the issue since we merged the PR.
