### ISSUE TITLE
Update the trace API implementation to firstValid API according to sidetree-core implementation spec

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree-bitcoin#35]

**Comment by srinathsetty** [comment]
Where is the spec for the new API? I still see an older spec on master.

**Comment by thehenrytsai** [comment]
Hi @srinathsetty, I was hoping to send out the PR together with the tests with core code change. But since you are blocked, I'll send a PR shortly without the tests to unblock you.

**Comment by srinathsetty** [comment]
Closing since the PR was merged with master.
